// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_proto_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserUserUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUserUUIDRequest) Reset() {
	*x = GetUserUserUUIDRequest{}
	mi := &file_proto_users_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUserUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUserUUIDRequest) ProtoMessage() {}

func (x *GetUserUserUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUserUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserUserUUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserUserUUIDRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type GetUserUserUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUserUUIDResponse) Reset() {
	*x = GetUserUserUUIDResponse{}
	mi := &file_proto_users_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUserUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUserUUIDResponse) ProtoMessage() {}

func (x *GetUserUserUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUserUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserUserUUIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserUserUUIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type PutUserUserUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutUserUserUUIDRequest) Reset() {
	*x = PutUserUserUUIDRequest{}
	mi := &file_proto_users_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutUserUserUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutUserUserUUIDRequest) ProtoMessage() {}

func (x *PutUserUserUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutUserUserUUIDRequest.ProtoReflect.Descriptor instead.
func (*PutUserUserUUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *PutUserUserUUIDRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type PutUserUserUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutUserUserUUIDResponse) Reset() {
	*x = PutUserUserUUIDResponse{}
	mi := &file_proto_users_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutUserUserUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutUserUserUUIDResponse) ProtoMessage() {}

func (x *PutUserUserUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutUserUserUUIDResponse.ProtoReflect.Descriptor instead.
func (*PutUserUserUUIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{8}
}

func (x *PutUserUserUUIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_users_users_proto protoreflect.FileDescriptor

const file_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x17proto/users/users.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bfullName\x18\x04 \x01(\tR\bfullName\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\tdeletedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"4\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"0\n" +
	"\x12CreateUserResponse\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\")\n" +
	"\x11LoginUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"4\n" +
	"\x16GetUserUserUUIDRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\":\n" +
	"\x17GetUserUserUUIDResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"4\n" +
	"\x16PutUserUserUUIDRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\":\n" +
	"\x17PutUserUserUUIDResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user2\xb4\x02\n" +
	"\vUserService\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12>\n" +
	"\tLoginUser\x12\x17.users.LoginUserRequest\x1a\x18.users.LoginUserResponse\x12P\n" +
	"\x0fGetUserUserUUID\x12\x1d.users.GetUserUserUUIDRequest\x1a\x1e.users.GetUserUserUUIDResponse\x12P\n" +
	"\x0fPutUserUserUUID\x12\x1d.users.PutUserUserUUIDRequest\x1a\x1e.users.PutUserUserUUIDResponseB=Z;github.com/rightDesire/facultativeproject/proto/users;usersb\x06proto3"

var (
	file_proto_users_users_proto_rawDescOnce sync.Once
	file_proto_users_users_proto_rawDescData []byte
)

func file_proto_users_users_proto_rawDescGZIP() []byte {
	file_proto_users_users_proto_rawDescOnce.Do(func() {
		file_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_users_users_proto_rawDesc), len(file_proto_users_users_proto_rawDesc)))
	})
	return file_proto_users_users_proto_rawDescData
}

var file_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_users_users_proto_goTypes = []any{
	(*User)(nil),                    // 0: users.User
	(*CreateUserRequest)(nil),       // 1: users.CreateUserRequest
	(*CreateUserResponse)(nil),      // 2: users.CreateUserResponse
	(*LoginUserRequest)(nil),        // 3: users.LoginUserRequest
	(*LoginUserResponse)(nil),       // 4: users.LoginUserResponse
	(*GetUserUserUUIDRequest)(nil),  // 5: users.GetUserUserUUIDRequest
	(*GetUserUserUUIDResponse)(nil), // 6: users.GetUserUserUUIDResponse
	(*PutUserUserUUIDRequest)(nil),  // 7: users.PutUserUserUUIDRequest
	(*PutUserUserUUIDResponse)(nil), // 8: users.PutUserUserUUIDResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_users_users_proto_depIdxs = []int32{
	9,  // 0: users.User.createdAt:type_name -> google.protobuf.Timestamp
	9,  // 1: users.User.updatedAt:type_name -> google.protobuf.Timestamp
	9,  // 2: users.User.deletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: users.CreateUserRequest.user:type_name -> users.User
	0,  // 4: users.GetUserUserUUIDResponse.user:type_name -> users.User
	0,  // 5: users.PutUserUserUUIDResponse.user:type_name -> users.User
	1,  // 6: users.UserService.CreateUser:input_type -> users.CreateUserRequest
	3,  // 7: users.UserService.LoginUser:input_type -> users.LoginUserRequest
	5,  // 8: users.UserService.GetUserUserUUID:input_type -> users.GetUserUserUUIDRequest
	7,  // 9: users.UserService.PutUserUserUUID:input_type -> users.PutUserUserUUIDRequest
	2,  // 10: users.UserService.CreateUser:output_type -> users.CreateUserResponse
	4,  // 11: users.UserService.LoginUser:output_type -> users.LoginUserResponse
	6,  // 12: users.UserService.GetUserUserUUID:output_type -> users.GetUserUserUUIDResponse
	8,  // 13: users.UserService.PutUserUserUUID:output_type -> users.PutUserUserUUIDResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_users_users_proto_init() }
func file_proto_users_users_proto_init() {
	if File_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_users_users_proto_rawDesc), len(file_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_users_users_proto_goTypes,
		DependencyIndexes: file_proto_users_users_proto_depIdxs,
		MessageInfos:      file_proto_users_users_proto_msgTypes,
	}.Build()
	File_proto_users_users_proto = out.File
	file_proto_users_users_proto_goTypes = nil
	file_proto_users_users_proto_depIdxs = nil
}
