// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: users/users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRepository_CreateUser_FullMethodName      = "/users.UserRepository/CreateUser"
	UserRepository_LoginUser_FullMethodName       = "/users.UserRepository/LoginUser"
	UserRepository_GetUserUserUUID_FullMethodName = "/users.UserRepository/GetUserUserUUID"
	UserRepository_PutUserUserUUID_FullMethodName = "/users.UserRepository/PutUserUserUUID"
)

// UserRepositoryClient is the client API for UserRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис репозитория, определяющий RPC-методы.
type UserRepositoryClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	GetUserUserUUID(ctx context.Context, in *GetUserUserUUIDRequest, opts ...grpc.CallOption) (*GetUserUserUUIDResponse, error)
	PutUserUserUUID(ctx context.Context, in *PutUserUserUUIDRequest, opts ...grpc.CallOption) (*PutUserUserUUIDResponse, error)
}

type userRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRepositoryClient(cc grpc.ClientConnInterface) UserRepositoryClient {
	return &userRepositoryClient{cc}
}

func (c *userRepositoryClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserRepository_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, UserRepository_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) GetUserUserUUID(ctx context.Context, in *GetUserUserUUIDRequest, opts ...grpc.CallOption) (*GetUserUserUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserUserUUIDResponse)
	err := c.cc.Invoke(ctx, UserRepository_GetUserUserUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) PutUserUserUUID(ctx context.Context, in *PutUserUserUUIDRequest, opts ...grpc.CallOption) (*PutUserUserUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutUserUserUUIDResponse)
	err := c.cc.Invoke(ctx, UserRepository_PutUserUserUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRepositoryServer is the server API for UserRepository service.
// All implementations must embed UnimplementedUserRepositoryServer
// for forward compatibility.
//
// Сервис репозитория, определяющий RPC-методы.
type UserRepositoryServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	GetUserUserUUID(context.Context, *GetUserUserUUIDRequest) (*GetUserUserUUIDResponse, error)
	PutUserUserUUID(context.Context, *PutUserUserUUIDRequest) (*PutUserUserUUIDResponse, error)
	mustEmbedUnimplementedUserRepositoryServer()
}

// UnimplementedUserRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRepositoryServer struct{}

func (UnimplementedUserRepositoryServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserRepositoryServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedUserRepositoryServer) GetUserUserUUID(context.Context, *GetUserUserUUIDRequest) (*GetUserUserUUIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUserUUID not implemented")
}
func (UnimplementedUserRepositoryServer) PutUserUserUUID(context.Context, *PutUserUserUUIDRequest) (*PutUserUserUUIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUserUserUUID not implemented")
}
func (UnimplementedUserRepositoryServer) mustEmbedUnimplementedUserRepositoryServer() {}
func (UnimplementedUserRepositoryServer) testEmbeddedByValue()                        {}

// UnsafeUserRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRepositoryServer will
// result in compilation errors.
type UnsafeUserRepositoryServer interface {
	mustEmbedUnimplementedUserRepositoryServer()
}

func RegisterUserRepositoryServer(s grpc.ServiceRegistrar, srv UserRepositoryServer) {
	// If the following call pancis, it indicates UnimplementedUserRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRepository_ServiceDesc, srv)
}

func _UserRepository_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_GetUserUserUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserUserUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).GetUserUserUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_GetUserUserUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).GetUserUserUUID(ctx, req.(*GetUserUserUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_PutUserUserUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutUserUserUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).PutUserUserUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_PutUserUserUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).PutUserUserUUID(ctx, req.(*PutUserUserUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRepository_ServiceDesc is the grpc.ServiceDesc for UserRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserRepository",
	HandlerType: (*UserRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserRepository_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserRepository_LoginUser_Handler,
		},
		{
			MethodName: "GetUserUserUUID",
			Handler:    _UserRepository_GetUserUserUUID_Handler,
		},
		{
			MethodName: "PutUserUserUUID",
			Handler:    _UserRepository_PutUserUserUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/users.proto",
}
