// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rightDesire/facultativeproject/api/internal/configs"
)

// Injectors from wire.go:

func InitApp() *App {
	configsConfigs := configs.NewConfigsFromEnv()
	app := NewApp(configsConfigs)
	return app
}
